name: ml-density
channels:
  - defaults
dependencies:
  - python=3.13
  - numpy=2.3
  - pip=25.2
  - scipy=1.16.2
  - numba=0.62.1
  - mpi4py=4.0.3
  - pip:
    - ase==3.26
    - wigners==0.3
    - metatensor-core==0.1.17
    - metatensor-operations==0.3.4
    - featomic==0.6.3
    - git+https://github.com/lcmd-epfl/Q-stack.git@master
